import './styles.css';

const s = (name: string) => `gss-${name}`;

export const schemaSearch = s('schemaSearch');
export const header = s('header');
export const input = s('input');
export const filters = s('filters');
export const filterChip = s('filterChip');
export const filterChipActive = s('filterChipActive');
export const results = s('results');
export const sectionHeader = s('sectionHeader');
export const argsHeader = s('argsHeader');
export const item = s('item');
export const itemName = s('itemName');
export const itemTypePrefix = s('itemTypePrefix');
export const itemKind = s('itemKind');
export const detail = s('detail');
export const detailHeader = s('detailHeader');
export const backBtn = s('backBtn');
export const typeName = s('typeName');
export const typeKindBadge = s('typeKindBadge');
export const typeImplements = s('typeImplements');
export const typeDescription = s('typeDescription');
export const fieldItem = s('fieldItem');
export const fieldItemExpanded = s('fieldItemExpanded');
export const fieldItemRow = s('fieldItemRow');
export const fieldItemDesc = s('fieldItemDesc');
export const fieldName = s('fieldName');
export const fieldArgs = s('fieldArgs');
export const fieldReturn = s('fieldReturn');
export const fieldDefault = s('fieldDefault');
export const noResults = s('noResults');
export const count = s('count');
export const tabs = s('tabs');
export const tab = s('tab');
export const tabActive = s('tabActive');
export const enumValue = s('enumValue');
export const possibleType = s('possibleType');
export const fieldDetailArgs = s('fieldDetailArgs');
export const fieldDetailArg = s('fieldDetailArg');
export const fieldDetailArgDesc = s('fieldDetailArgDesc');
